export { default as getUsers } from './getUsers'
export { default as registerUser } from './registerUser'
export { default as login } from './login'
export { default as deleteUser } from './deleteUser'
export { default as getUser } from './getUser'
