defaults: &defaults
  docker:
    - image: circleci/node:10.15.0
  working_directory: ~/tmp/circlci-now

version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/tmp/circlci-now
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: yarn install
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths: .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/tmp/circlci-now
      - run:
          name: Install Now CLI
          command: yarn add global now
      - deploy:
          name: Deploy & Alias
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                now --token $ZEIT_TOKEN --local-config .now/now.production.json
                now --token $ZEIT_TOKEN --local-config .now/now.production.json alias
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
                now --token $ZEIT_TOKEN --local-config .now/now.staging.json
                now --token $ZEIT_TOKEN --local-config .now/now.staging.json alias
            else
                ./.now/now.feature.sh
                now --token $ZEIT_TOKEN --local-config .now/now.feature.json
                now --token $ZEIT_TOKEN --local-config .now/now.feature.json alias
            fi
workflows:
  version: 2
  test-deploy-purge:
    jobs:
      - checkout
      - deploy:
          requires:
            - checkout
